server:
  port: 8080
  contextPath: /document-base-web

spring:
  application.name: document-base-web

  datasource.schema: classpath:/data/hsqldb/structure.sql
  datasource.data: classpath:/data/hsqldb/insert.sql

  jpa.properties.hibernate:
    show_sql: true
    format_sql: true
    enable_lazy_load_no_trans: true
    max_fetch_depth: 3
    jdbc.fetch_size: 50
    jdbc.batch_size: 10

logging.level:
    org.hibernate:
#      type: TRACE
      SQL: TRACE